### ISSUE TITLE
Compatibility with Owncloud <= 8.2

### ISSUE THREAD

**Issue by e-alfred** [arno01/ocdec#4]
Hello,

is the script compatible with Owncloud 8.2 and up? It would be really useful for these versions as well.

Thank you

**Comment by arno01** [comment]
Hello,
it should be, if their code didn't change much.
I haven't tried, but you can try and report in here ;-)

Thanks,
Cheers

**Comment by arno01** [comment]
Closing for now... please feel free to re-open it in case if it does not work in owncloud <= 8.2.
